# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QDataLabel_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DataLabel_select(object):
    def setupUi(self, DataLabel_select):
        DataLabel_select.setObjectName("DataLabel_select")
        DataLabel_select.setEnabled(True)
        DataLabel_select.resize(314, 143)
        self.gridLayout = QtWidgets.QGridLayout(DataLabel_select)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox = QtWidgets.QComboBox(DataLabel_select)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(DataLabel_select)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_2.setPalette(palette)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 2)
        self.label = QtWidgets.QLabel(DataLabel_select)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.Yes = QtWidgets.QPushButton(DataLabel_select)
        self.Yes.setObjectName("Yes")
        self.gridLayout.addWidget(self.Yes, 2, 0, 1, 1)
        self.Cancel = QtWidgets.QPushButton(DataLabel_select)
        self.Cancel.setObjectName("Cancel")
        self.gridLayout.addWidget(self.Cancel, 2, 1, 1, 1)

        self.retranslateUi(DataLabel_select)
        self.Yes.clicked.connect(DataLabel_select.accept) # type: ignore
        self.Cancel.clicked.connect(DataLabel_select.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DataLabel_select)

    def retranslateUi(self, DataLabel_select):
        _translate = QtCore.QCoreApplication.translate
        DataLabel_select.setWindowTitle(_translate("DataLabel_select", "DataLabel_select"))
        self.label_2.setText(_translate("DataLabel_select", "Because dimension reduction will change the features, \n"
" select the label features that you want to retain.\n"
" (Note that other parameters cannot be restored \n"
" to their original parameters after this step.)"))
        self.label.setText(_translate("DataLabel_select", "LabelFeature:"))
        self.Yes.setText(_translate("DataLabel_select", "Yes"))
        self.Cancel.setText(_translate("DataLabel_select", "Cancel"))
